// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVH7O1ZIHXvW2aO_SHLcpYCbcbPaA3w94',
    appId: '1:765982982230:web:3c1b05b5b2c7d5c1e3bbf7',
    messagingSenderId: '765982982230',
    projectId: 'payguardian-8f7ae',
    authDomain: 'payguardian-8f7ae.firebaseapp.com',
    storageBucket: 'payguardian-8f7ae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKpBZrZ1dxxoaEHRW3QOcThCAeJi3jbbo',
    appId: '1:765982982230:android:2b1e879227eb34dbe3bbf7',
    messagingSenderId: '765982982230',
    projectId: 'payguardian-8f7ae',
    storageBucket: 'payguardian-8f7ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGdoUQArRMG7o6qGO9zrBBBo169KviFjo',
    appId: '1:765982982230:ios:2590e0be7b7e512ee3bbf7',
    messagingSenderId: '765982982230',
    projectId: 'payguardian-8f7ae',
    storageBucket: 'payguardian-8f7ae.firebasestorage.app',
    iosBundleId: 'com.example.payguardian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGdoUQArRMG7o6qGO9zrBBBo169KviFjo',
    appId: '1:765982982230:ios:2590e0be7b7e512ee3bbf7',
    messagingSenderId: '765982982230',
    projectId: 'payguardian-8f7ae',
    storageBucket: 'payguardian-8f7ae.firebasestorage.app',
    iosBundleId: 'com.example.payguardian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVH7O1ZIHXvW2aO_SHLcpYCbcbPaA3w94',
    appId: '1:765982982230:web:495877f2483acc2fe3bbf7',
    messagingSenderId: '765982982230',
    projectId: 'payguardian-8f7ae',
    authDomain: 'payguardian-8f7ae.firebaseapp.com',
    storageBucket: 'payguardian-8f7ae.firebasestorage.app',
  );
}
